### ISSUE TITLE
Use <stdint.h> types

### ISSUE THREAD

**Issue by alejandro-colomar** [xbarin02/collatz#2]
Hi,

You use `unsigned long` instead of `uint64_t`, because GMP forces you to do so.

I had the same problem with [GSL](https://www.gnu.org/software/gsl/) , and I solved it writing a wrapper around its functions, and adding some compile-time assertions to ensure that the types are the same.

I would like to show you an example of what I did, so that if you like it, you can apply it to your code.  I think it will look better with `uint64_t`.

Assertions:
https://github.com/alejandro-colomar/libalx/blob/master/inc/libalx/base/assert/assert.h

Wrappers:
https://github.com/alejandro-colomar/libalx/blob/master/inc/libalx/extra/gsl/statistics/mean.h

You could either write wrappers (I would do that), or just assert that the types are the same and use the typedefs directly.

**Comment by xbarin02** [comment]
I am still considering the feasibility of a such solution. The problem is deeper than it seemed to be. My considerations have led me to the need to systematically wrap all functions, including the standard C functions. Consider for example `int atoi(const char *nptr);` declared in `<stdlib.h>` header. I would have to create wrappers such as:
```
int64_t atoi64(const char *nptr)
{
        switch(sizeof(int64_t)) {
                case sizeof(int): return atoi(nptr);
                case sizeof(long): return atol(nptr);
                case sizeof(long long): return atoll(nptr);
        }
}
```
Optimizing compiler would do their job... though. It's crazy a lot of work... I will still consider it, but at the moment I'm not sure if it's worth it.

**Comment by alejandro-colomar** [comment]
Huh, crazy lot of work... yes it was xD

I already did those (actually not atoi because it's unsafe, but strtol):

https://github.com/alejandro-colomar/libalx/blob/master/inc/libalx/base/stdlib/strto/strtoi_s.h
https://github.com/alejandro-colomar/libalx/blob/master/src/base/stdlib/strto/strtoi_s.c
https://github.com/alejandro-colomar/libalx/blob/master/inc/libalx/base/stdlib/strto/strtou_s.h
https://github.com/alejandro-colomar/libalx/blob/master/src/base/stdlib/strto/strtou_s.c

Feel free to inspect all of my [library](https://github.com/alejandro-colomar/libalx).  I had that problem some time ago, and started doing that crazy lot of work so that I could then write very simple programs.

My library relies on the latest standard + POSIX extensions + GNU extensions + BSD extensions (```-std=gnu17 -D _GNU_SOURCE  -D _POSIX_C_SOURCE=200809L `pkg-config --cflags libbsd-overlay` ```), but it could be ported to older standards and remove the libbsd dependency, although I would recommend to upgrade your code to use C17 instead.

If you prefer, you could just install it in your system and use it as an external library (either static or dynamic).

Here's a list of the headers I have now, which should give you an idea of what functions I wrote:

```
.
└── libalx
    ├── base
    │   ├── assert
    │   │   └── assert.h
    │   ├── compiler
    │   │   ├── size.h
    │   │   ├── type.h
    │   │   └── unused.h
    │   ├── errno
    │   │   └── error.h
    │   ├── float
    │   │   ├── constant.h
    │   │   ├── printf.h
    │   │   └── scanf.h
    │   ├── math
    │   │   ├── array_division.h
    │   │   ├── array_multiplication.h
    │   │   ├── array_sum.h
    │   │   ├── binomial_coefficient.h
    │   │   ├── matrix_addition.h
    │   │   ├── matrix_subtraction.h
    │   │   ├── pascal_triangle.h
    │   │   ├── prime_defactorization.h
    │   │   ├── prime_factorization.h
    │   │   ├── prime.h
    │   │   └── scale_linear.h
    │   ├── stdint
    │   │   ├── constants.h
    │   │   └── types.h
    │   ├── stdio
    │   │   ├── escape_sequences.h
    │   │   ├── get.h
    │   │   ├── printf
    │   │   │   ├── b.h
    │   │   │   ├── sbprintf.h
    │   │   │   └── snprintfs.h
    │   │   ├── seekc.h
    │   │   └── sscan.h
    │   ├── stdlib
    │   │   ├── alloc
    │   │   │   ├── callocs.h
    │   │   │   ├── mallocarray.h
    │   │   │   ├── mallocs.h
    │   │   │   └── reallocs.h
    │   │   ├── array_split_pos_neg.h
    │   │   ├── average.h
    │   │   ├── compare.h
    │   │   ├── local_maxima.h
    │   │   ├── maximum.h
    │   │   ├── minimum.h
    │   │   ├── popcnt.h
    │   │   ├── pow.h
    │   │   ├── search.h
    │   │   ├── seed.h
    │   │   ├── strto
    │   │   │   ├── strtof_s.h
    │   │   │   ├── strtoi_s.h
    │   │   │   └── strtou_s.h
    │   │   └── swap.h
    │   └── string
    │       ├── strcat
    │       │   └── strscat.h
    │       ├── strchr
    │       │   ├── strcasechr.h
    │       │   ├── strcasechrnul.h
    │       │   ├── strncasechr.h
    │       │   ├── strncasechrnul.h
    │       │   ├── strnchr.h
    │       │   ├── strnchrnul.h
    │       │   ├── strnrcasechr.h
    │       │   ├── strnrcasechrnul.h
    │       │   ├── strnrchr.h
    │       │   ├── strnrchrnul.h
    │       │   ├── strrcasechr.h
    │       │   ├── strrcasechrnul.h
    │       │   └── strrchrnul.h
    │       ├── strcpy
    │       │   └── strscpy.h
    │       ├── strgrep.h
    │       └── strstr
    │           ├── strncasestr.h
    │           ├── strscasestr.h
    │           └── strsstr.h
    └── extra
        ├── cv
        │   ├── alx.h
        │   ├── core.h
        │   ├── features2d.h
        │   ├── highgui.h
        │   ├── imgproc.h
        │   └── ximgproc.h
        ├── gsl
        │   ├── distributions
        │   │   ├── binomial.h
        │   │   ├── exponential.h
        │   │   ├── geometric.h
        │   │   ├── normal.h
        │   │   ├── poisson.h
        │   │   └── uniform.h
        │   ├── rstat
        │   │   └── median.h
        │   └── statistics
        │       └── mean.h
        ├── ncurses
        │   ├── common.h
        │   ├── get.h
        │   ├── menu.h
        │   └── perror.h
        ├── ocr
        │   └── ocr.h
        └── zbar
            └── zbar.h
```

**Comment by alejandro-colomar** [comment]
What I did to make my life easier, is to only support amd64 & Linux, so `long` is always 64 b, `int` is 32 b, etc.  And if it isn't, I just break the compilation.  I thought about doing it generic so that I could support for example embedded systems, but that woud be even more crazy, so I don't think I'll do that any soon.

**Comment by alejandro-colomar** [comment]
I just wrote wrappers for all the gmp functions that use standard C integers.  Here are links to the ones you use in your code:

mpz_ui_pow_ui()	->	alx_mpz_u64_pow_u64()
https://github.com/alejandro-colomar/libalx/blob/master/inc/libalx/extra/gmp/mpz/exp.h

mpz_init_set_ui()	->	alx_mpz_init_set_u64()
https://github.com/alejandro-colomar/libalx/blob/master/inc/libalx/extra/gmp/mpz/init_set.h

mpz_add_ui()		->	alx_mpz_add_u64()
mpz_sub_ui()		->	alx_mpz_sub_u64()
https://github.com/alejandro-colomar/libalx/blob/master/inc/libalx/extra/gmp/mpz/arithmetic.h

**Comment by xbarin02** [comment]
Hi,

I still plan to resolve this issue. I'm just overwhelmed with other work. My priority now is a reliable protocol between the server and clients so that clients cannot cheat (double check, i.e. assign the same block to two different clients and verify whether they return the same control check)...
