### ISSUE TITLE
cl.h is missing

### ISSUE THREAD

**Issue by Calebtheaa** [xbarin02/collatz#6]
When compiling the gpuworker, I'm getting a fatal error from CL/cl.h being missing. There isn't any file in the repository for this file, so how do I get it?

`
cc -std=c89 -pedantic -Wall -Wextra -march=native -O3 -D_XOPEN_SOURCE=500 -DCL_TARGET_OPENCL_VERSION=220 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DSIEVE_LOGSIZE=16 -DTASK_UNITS=16 -DUSE_ASYNC_CALL     gpuworker.c  -lOpenCL  -o `
`gpuworker`
`gpuworker.c:11:10: fatal error: CL/cl.h: No such file or directory`
`   11 | #include <CL/cl.h>`
`      |          ^~~~~~~~~`
`compilation terminated.`
`make: *** [<builtin>: gpuworker] Error 1`

**Comment by xbarin02** [comment]
You need to install opencl-headers. Later you will also need a GPU driver with opencl support.

**Comment by Calebtheaa** [comment]
Thanks, it worked.
