### ISSUE TITLE
Can we contribute using BOINC?

### ISSUE THREAD

**Issue by gamer191** [xbarin02/collatz#7]
Since the website isn't clear, I'm just wondering if this project is distributed (such as BOINC) or if this project just runs on your computer?

**Comment by xbarin02** [comment]
Yes, it is distributed computing project. Clients are run by job scheduling systems in the infrastructure of various supercomputers in Europe. However, this is currently a closed project (external users cannot participate). If you want to get involved, you can start a server in your own infrastructure. You can then run the clients on your computers. Another way to participate is to optimize the source codes and send me a pull request.
